name: Release

on:
  push:
    branches: [master]

permissions: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release_please:
    name: Stage or create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Update release pull request
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build:
    name: Build release distributions
    if: needs.release_please.outputs.release_created == 'true'
    needs: release_please
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.3
      - name: Build and inspect distributions
        run: pixi run package
      - name: Store distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-distributions
          path: dist/
          if-no-files-found: error

  publish:
    name: Publish release to PyPI
    if: needs.release_please.outputs.release_created == 'true'
    needs: [release_please, build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/uogtad
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-distributions
          path: dist/
      - name: Publish distributions
        uses: pypa/gh-action-pypi-publish@release/v1
